//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dracoon.Crypto.Sdk.Test {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dracoon.Crypto.Sdk.Test.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_aes256gcm_enc_file {
            get {
                object obj = ResourceManager.GetObject("csharp_aes256gcm_enc_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_fk_rsa2048_aes256gcm_enc_file_key {
            get {
                object obj = ResourceManager.GetObject("csharp_fk_rsa2048_aes256gcm_enc_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_fk_rsa2048_aes256gcm_plain_file_key {
            get {
                object obj = ResourceManager.GetObject("csharp_fk_rsa2048_aes256gcm_plain_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_fk_rsa4096_aes256gcm_enc_file_key {
            get {
                object obj = ResourceManager.GetObject("csharp_fk_rsa4096_aes256gcm_enc_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_fk_rsa4096_aes256gcm_plain_file_key {
            get {
                object obj = ResourceManager.GetObject("csharp_fk_rsa4096_aes256gcm_plain_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_kp_rsa2048_private_key {
            get {
                object obj = ResourceManager.GetObject("csharp_kp_rsa2048_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_kp_rsa2048_public_key {
            get {
                object obj = ResourceManager.GetObject("csharp_kp_rsa2048_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_kp_rsa4096_pbkdf2_sha1_1300k_private_key {
            get {
                object obj = ResourceManager.GetObject("csharp_kp_rsa4096_pbkdf2_sha1_1300k_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_kp_rsa4096_pbkdf2_sha1_1300k_public_key {
            get {
                object obj = ResourceManager.GetObject("csharp_kp_rsa4096_pbkdf2_sha1_1300k_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_kp_rsa4096_private_key {
            get {
                object obj = ResourceManager.GetObject("csharp_kp_rsa4096_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_kp_rsa4096_public_key {
            get {
                object obj = ResourceManager.GetObject("csharp_kp_rsa4096_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_kp_rsa4096_utf8_umlaut_emoji_private_key {
            get {
                object obj = ResourceManager.GetObject("csharp_kp_rsa4096_utf8_umlaut_emoji_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_kp_rsa4096_utf8_umlaut_emoji_public_key {
            get {
                object obj = ResourceManager.GetObject("csharp_kp_rsa4096_utf8_umlaut_emoji_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] csharp_plain_file {
            get {
                object obj = ResourceManager.GetObject("csharp_plain_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] enc_file_key_bad_iv {
            get {
                object obj = ResourceManager.GetObject("enc_file_key_bad_iv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] enc_file_key_bad_key {
            get {
                object obj = ResourceManager.GetObject("enc_file_key_bad_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] enc_file_key_bad_tag {
            get {
                object obj = ResourceManager.GetObject("enc_file_key_bad_tag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] enc_file_key_bad_version {
            get {
                object obj = ResourceManager.GetObject("enc_file_key_bad_version", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XZoZFAZekI+xyaI6Kirb/6PfGvjH0Gi5EPA5XU49OFt9wqdDsISEtvSKQ6ISgOZ+mso= ähnelt.
        /// </summary>
        internal static string enc_file_modified {
            get {
                return ResourceManager.GetString("enc_file_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_aes256gcm_enc_file {
            get {
                object obj = ResourceManager.GetObject("java_aes256gcm_enc_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_fk_rsa2048_aes256gcm_enc_file_key {
            get {
                object obj = ResourceManager.GetObject("java_fk_rsa2048_aes256gcm_enc_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_fk_rsa2048_aes256gcm_plain_file_key {
            get {
                object obj = ResourceManager.GetObject("java_fk_rsa2048_aes256gcm_plain_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_fk_rsa4096_aes256gcm_enc_file_key {
            get {
                object obj = ResourceManager.GetObject("java_fk_rsa4096_aes256gcm_enc_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_fk_rsa4096_aes256gcm_plain_file_key {
            get {
                object obj = ResourceManager.GetObject("java_fk_rsa4096_aes256gcm_plain_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_kp_rsa2048_private_key {
            get {
                object obj = ResourceManager.GetObject("java_kp_rsa2048_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_kp_rsa2048_public_key {
            get {
                object obj = ResourceManager.GetObject("java_kp_rsa2048_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_kp_rsa4096_iso_umlaut_private_key {
            get {
                object obj = ResourceManager.GetObject("java_kp_rsa4096_iso_umlaut_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_kp_rsa4096_iso_umlaut_public_key {
            get {
                object obj = ResourceManager.GetObject("java_kp_rsa4096_iso_umlaut_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_kp_rsa4096_pbkdf2_sha1_1300k_private_key {
            get {
                object obj = ResourceManager.GetObject("java_kp_rsa4096_pbkdf2_sha1_1300k_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_kp_rsa4096_pbkdf2_sha1_1300k_public_key {
            get {
                object obj = ResourceManager.GetObject("java_kp_rsa4096_pbkdf2_sha1_1300k_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_kp_rsa4096_private_key {
            get {
                object obj = ResourceManager.GetObject("java_kp_rsa4096_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_kp_rsa4096_public_key {
            get {
                object obj = ResourceManager.GetObject("java_kp_rsa4096_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_kp_rsa4096_utf8_umlaut_emoji_private_key {
            get {
                object obj = ResourceManager.GetObject("java_kp_rsa4096_utf8_umlaut_emoji_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_kp_rsa4096_utf8_umlaut_emoji_public_key {
            get {
                object obj = ResourceManager.GetObject("java_kp_rsa4096_utf8_umlaut_emoji_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] java_plain_file {
            get {
                object obj = ResourceManager.GetObject("java_plain_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_aes256gcm_enc_file {
            get {
                object obj = ResourceManager.GetObject("js_aes256gcm_enc_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_fk_rsa2048_aes256gcm_enc_file_key {
            get {
                object obj = ResourceManager.GetObject("js_fk_rsa2048_aes256gcm_enc_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_fk_rsa2048_aes256gcm_plain_file_key {
            get {
                object obj = ResourceManager.GetObject("js_fk_rsa2048_aes256gcm_plain_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_fk_rsa4096_aes256gcm_enc_file_key {
            get {
                object obj = ResourceManager.GetObject("js_fk_rsa4096_aes256gcm_enc_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_fk_rsa4096_aes256gcm_plain_file_key {
            get {
                object obj = ResourceManager.GetObject("js_fk_rsa4096_aes256gcm_plain_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_kp_rsa2048_private_key {
            get {
                object obj = ResourceManager.GetObject("js_kp_rsa2048_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_kp_rsa2048_public_key {
            get {
                object obj = ResourceManager.GetObject("js_kp_rsa2048_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_kp_rsa4096_iso_umlaut_private_key {
            get {
                object obj = ResourceManager.GetObject("js_kp_rsa4096_iso_umlaut_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_kp_rsa4096_iso_umlaut_public_key {
            get {
                object obj = ResourceManager.GetObject("js_kp_rsa4096_iso_umlaut_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_kp_rsa4096_pbkdf2_sha1_1300k_private_key {
            get {
                object obj = ResourceManager.GetObject("js_kp_rsa4096_pbkdf2_sha1_1300k_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_kp_rsa4096_pbkdf2_sha1_1300k_public_key {
            get {
                object obj = ResourceManager.GetObject("js_kp_rsa4096_pbkdf2_sha1_1300k_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_kp_rsa4096_private_key {
            get {
                object obj = ResourceManager.GetObject("js_kp_rsa4096_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_kp_rsa4096_public_key {
            get {
                object obj = ResourceManager.GetObject("js_kp_rsa4096_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_kp_rsa4096_utf8_umlaut_emoji_private_key {
            get {
                object obj = ResourceManager.GetObject("js_kp_rsa4096_utf8_umlaut_emoji_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_kp_rsa4096_utf8_umlaut_emoji_public_key {
            get {
                object obj = ResourceManager.GetObject("js_kp_rsa4096_utf8_umlaut_emoji_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] js_plain_file {
            get {
                object obj = ResourceManager.GetObject("js_plain_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] plain_file_key_bad_iv {
            get {
                object obj = ResourceManager.GetObject("plain_file_key_bad_iv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] plain_file_key_bad_key {
            get {
                object obj = ResourceManager.GetObject("plain_file_key_bad_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] plain_file_key_bad_tag {
            get {
                object obj = ResourceManager.GetObject("plain_file_key_bad_tag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XGVzdEFCQ0RFRkdIIDEyMwpUZXN0SUpLTE1OT1AgNDU2ClRlc3RRUlNUVVZXWCA3ODk= ähnelt.
        /// </summary>
        internal static string plain_file_modified {
            get {
                return ResourceManager.GetString("plain_file_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] private_key_bad_asn1 {
            get {
                object obj = ResourceManager.GetObject("private_key_bad_asn1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] private_key_bad_pem {
            get {
                object obj = ResourceManager.GetObject("private_key_bad_pem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] private_key_bad_value {
            get {
                object obj = ResourceManager.GetObject("private_key_bad_value", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] private_key_bad_version {
            get {
                object obj = ResourceManager.GetObject("private_key_bad_version", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] ruby_aes256gcm_enc_file {
            get {
                object obj = ResourceManager.GetObject("ruby_aes256gcm_enc_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] ruby_fk_rsa2048_aes256gcm_enc_file_key {
            get {
                object obj = ResourceManager.GetObject("ruby_fk_rsa2048_aes256gcm_enc_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] ruby_fk_rsa2048_aes256gcm_plain_file_key {
            get {
                object obj = ResourceManager.GetObject("ruby_fk_rsa2048_aes256gcm_plain_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] ruby_fk_rsa4096_aes256gcm_enc_file_key {
            get {
                object obj = ResourceManager.GetObject("ruby_fk_rsa4096_aes256gcm_enc_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] ruby_fk_rsa4096_aes256gcm_plain_file_key {
            get {
                object obj = ResourceManager.GetObject("ruby_fk_rsa4096_aes256gcm_plain_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] ruby_kp_rsa2048_private_key {
            get {
                object obj = ResourceManager.GetObject("ruby_kp_rsa2048_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] ruby_kp_rsa2048_public_key {
            get {
                object obj = ResourceManager.GetObject("ruby_kp_rsa2048_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] ruby_kp_rsa4096_private_key {
            get {
                object obj = ResourceManager.GetObject("ruby_kp_rsa4096_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] ruby_kp_rsa4096_public_key {
            get {
                object obj = ResourceManager.GetObject("ruby_kp_rsa4096_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] ruby_plain_file {
            get {
                object obj = ResourceManager.GetObject("ruby_plain_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_aes256gcm_enc_file {
            get {
                object obj = ResourceManager.GetObject("swift_aes256gcm_enc_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_fk_rsa2048_aes256gcm_enc_file_key {
            get {
                object obj = ResourceManager.GetObject("swift_fk_rsa2048_aes256gcm_enc_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_fk_rsa2048_aes256gcm_plain_file_key {
            get {
                object obj = ResourceManager.GetObject("swift_fk_rsa2048_aes256gcm_plain_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_fk_rsa4096_aes256gcm_enc_file_key {
            get {
                object obj = ResourceManager.GetObject("swift_fk_rsa4096_aes256gcm_enc_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_fk_rsa4096_aes256gcm_plain_file_key {
            get {
                object obj = ResourceManager.GetObject("swift_fk_rsa4096_aes256gcm_plain_file_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_kp_rsa2048_private_key {
            get {
                object obj = ResourceManager.GetObject("swift_kp_rsa2048_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_kp_rsa2048_public_key {
            get {
                object obj = ResourceManager.GetObject("swift_kp_rsa2048_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_kp_rsa4096_pbkdf2_sha1_1300k_private_key {
            get {
                object obj = ResourceManager.GetObject("swift_kp_rsa4096_pbkdf2_sha1_1300k_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_kp_rsa4096_pbkdf2_sha1_1300k_public_key {
            get {
                object obj = ResourceManager.GetObject("swift_kp_rsa4096_pbkdf2_sha1_1300k_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_kp_rsa4096_private_key {
            get {
                object obj = ResourceManager.GetObject("swift_kp_rsa4096_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_kp_rsa4096_public_key {
            get {
                object obj = ResourceManager.GetObject("swift_kp_rsa4096_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_kp_utf8_umlaut_emoji_private_key {
            get {
                object obj = ResourceManager.GetObject("swift_kp_utf8_umlaut_emoji_private_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_kp_utf8_umlaut_emoji_public_key {
            get {
                object obj = ResourceManager.GetObject("swift_kp_utf8_umlaut_emoji_public_key", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] swift_plain_file {
            get {
                object obj = ResourceManager.GetObject("swift_plain_file", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
